- name: Remove enterprise repo
  file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent

- name: Add no-subscription repo
  copy:
    dest: /etc/apt/sources.list.d/pve-no-subscription.list
    content: |
      deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription

- name: Remove Proxmox Ceph enterprise repo
  file:
    path: /etc/apt/sources.list.d/ceph.list
    state: absent
