- name: Install and configure Authelia
  hosts: authelia
  become: true
  roles:
    - authelia
  vars_files:
    - ../vaults/authelia.yml # for password
  vars:
    authelia_user: authelia
    authelia_domain: "{{ authelia_domain }}"
    authelia_port: 9091
    authelia_session_secret: "{{ authelia_session_secret }}"
    authelia_config_path: /etc/authelia
    authelia_bin_dir: /opt/authelia
  vars_prompt:
    - name: authelia_password
      prompt: "Enter Authelia admin password"
      private: true
