- name: Ensure required packages are installed
  apt:
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
    state: present
    update_cache: yes

- name: Add Caddy APT signing key
  ansible.builtin.get_url:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    dest: /usr/share/keyrings/caddy-archive-keyring.gpg
    mode: "0644"

- name: Add Caddy APT repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/caddy-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian all main"
    state: present
    filename: caddy

- name: Install Caddy
  apt:
    name: caddy
    state: present
    update_cache: yes

- name: Ensure Caddy config directory exists
  file:
    path: "{{ caddy_config_dir }}"
    state: directory
    mode: "0755"

- name: Deploy Caddyfile
  template:
    src: Caddyfile.j2
    dest: "{{ caddy_config_file }}"
    mode: "0644"
    owner: root
    group: root
  notify: Restart Caddy

- name: Ensure Caddy is enabled and started
  systemd:
    name: caddy
    state: started
    enabled: yes
